import { PUNCTUATION } from './enums'
import elderFuthark from './elder-futhark'

export default {
  f: elderFuthark.fehu,
  u: elderFuthark.uruz,
  þ: elderFuthark.thurisaz,
  a: elderFuthark.ansuz,
  r: elderFuthark.raido,
  k: elderFuthark.kaunan,
  c: elderFuthark.kaunan,
  g: elderFuthark.gebo,
  w: elderFuthark.wunjo,
  h: elderFuthark.hagalaz,
  n: elderFuthark.naudiz,
  i: elderFuthark.isaz,
  j: elderFuthark.jera,
  y: elderFuthark.jera,
  æ: elderFuthark.eihwaz,
  ï: elderFuthark.eihwaz,
  p: elderFuthark.perth,
  z: elderFuthark.algiz,
  s: elderFuthark.sowilo,
  t: elderFuthark.tiwaz,
  b: elderFuthark.berkanan,
  e: elderFuthark.ehwaz,
  m: elderFuthark.mannaz,
  l: elderFuthark.laguz,
  ŋ: elderFuthark.ingwaz,
  o: elderFuthark.othala,
  d: elderFuthark.dagaz,
  v: elderFuthark.fehu,
  ð: elderFuthark.thurisaz,
  x: elderFuthark.kaunan + elderFuthark.sowilo,
  ch: elderFuthark.gebo,
  ij: elderFuthark.ehwaz,
  cc: elderFuthark.kaunan + elderFuthark.sowilo,
  th: elderFuthark.thurisaz,
  eau: elderFuthark.othala,
  chr: elderFuthark.hagalaz + elderFuthark.raido,
  ing: elderFuthark.ingwaz,
  chl: elderFuthark.hagalaz + elderFuthark.laguz,
  ng: elderFuthark.ingwaz,
  chj: elderFuthark.hagalaz + elderFuthark.jera,
  nk: elderFuthark.ingwaz + elderFuthark.kaunan,
  chw: elderFuthark.hagalaz + elderFuthark.wunjo,
  ei: elderFuthark.sowilo,
  ø: elderFuthark.othala + elderFuthark.ehwaz,
  å: elderFuthark.ansuz + elderFuthark.ansuz,
  q: elderFuthark.kaunan,
  punctuation: { [PUNCTUATION.SINGLE]: '᛫', [PUNCTUATION.DOUBLE]: '᛬', [PUNCTUATION.CROSS]: '᛭' } // punctuation variants
}
